import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

type PromptDefinition = {
  name: string;
  title: string;
  description: string;
  text: string;
};

const PROMPTS: PromptDefinition[] = [
  {
    name: "memento/operating-manual",
    title: "Memento Operating Manual",
    description: "How to store and retrieve artifacts with Memento MCP.",
    text: [
      "Memento operating manual:",
      "",
      "1) Resolve project context first:",
      "- projects.resolve (sets active project for this connection)",
      "- For restores, prefer repo_url or project_key (stable across machines); avoid cwd-only",
      "- Use create_if_missing=false when you expect the project to exist",
      "- sessions.start when beginning a focused work session",
      "",
      "2) Choose the right write tool:",
      "- canonical.upsert for stable, reusable docs (specs, plans, runbooks)",
      "- memory.commit for non-canonical or evolving artifacts (notes, ADRs, spikes)",
      "",
      "3) Always include:",
      "- doc_class (fine-grained type)",
      "- kind (broad bucket: spec/plan/architecture/decision/runbook/etc)",
      "- tags for retrieval (feature:<name>, area:<name>, doc:<type>)",
      "",
      "4) Link the lifecycle graph:",
      "- memory.link between spec/design/plan/test/rollout",
      "- ADRs link to spec/design they influence",
      "",
      "5) Retrieval best practices:",
      "- canonical.outline + canonical.get_section for targeted excerpts",
      "- memory.search for cross-cutting queries",
      "- memory.restore for session kickoff bundles",
      "",
      "6) Idempotency for writes:",
      "- All write tools require idempotency_key; reuse to dedupe safely.",
      "",
      "Follow-ups:",
      "- After upsert: canonical.outline, canonical.get_section, memory.link",
      "- After commit: memory.get, memory.history, memory.link",
    ].join("\n"),
  },
  {
    name: "memento/doc-class-taxonomy",
    title: "Doc Class Taxonomy",
    description: "Official doc_class list and mapping guidance.",
    text: [
      "Use these doc_class values for stored artifacts:",
      "",
      "Canonical lifecycle docs (prefer canonical.upsert):",
      "- app_spec: canonical_key=app, kind=spec",
      "- feature_spec: canonical_key=feature/<name>/spec, kind=spec",
      "- design_doc: canonical_key=feature/<name>/design, kind=architecture",
      "- architecture_doc: canonical_key=arch/overview or arch/<topic>, kind=architecture",
      "- implementation_plan: canonical_key=feature/<name>/plan, kind=plan",
      "- test_plan: canonical_key=feature/<name>/test, kind=plan",
      "- rollout_plan: canonical_key=feature/<name>/rollout, kind=plan",
      "- environment_registry: canonical_key=env/registry, kind=environment_fact",
      "- runbook: canonical_key=runbook/<service>/<task>, kind=runbook",
      "",
      "Non-canonical docs (prefer memory.commit):",
      "- adr (kind=decision; can be canonical if you want stable ADR keys)",
      "- code_map (kind=environment_fact or note)",
      "- troubleshooting (kind=troubleshooting)",
      "- postmortem (kind=troubleshooting)",
      "- meeting_notes (kind=note)",
      "- research_spike (kind=note)",
      "- onboarding_guide (kind=spec; can be canonical)",
      "- release_notes (kind=note or plan)",
      "- security_review (kind=architecture or spec)",
      "- performance_notes (kind=architecture or note)",
      "- glossary (kind=spec; can be canonical)",
    ].join("\n"),
  },
  {
    name: "memento/playbook-feature-lifecycle",
    title: "Feature Lifecycle Playbook",
    description: "Step-by-step workflow for spec -> design -> plan -> test -> rollout.",
    text: [
      "Feature lifecycle capture playbook (feature -> design -> plan -> test -> rollout):",
      "",
      "0) Session setup:",
      "- projects.resolve",
      "- sessions.start",
      "- memory.restore (goal = what you're doing)",
      "",
      "1) Ensure app spec exists (canonical):",
      "- canonical.upsert canonical_key=app doc_class=app_spec kind=spec (pinned)",
      "",
      "2) Create feature spec (canonical):",
      "- canonical.upsert canonical_key=feature/<name>/spec doc_class=feature_spec kind=spec",
      "",
      "3) Create design doc (canonical):",
      "- canonical.upsert canonical_key=feature/<name>/design doc_class=design_doc kind=architecture",
      "",
      "4) Create implementation plan (canonical):",
      "- canonical.upsert canonical_key=feature/<name>/plan doc_class=implementation_plan kind=plan",
      "",
      "5) Create test plan (canonical):",
      "- canonical.upsert canonical_key=feature/<name>/test doc_class=test_plan kind=plan",
      "",
      "6) Create rollout plan (canonical):",
      "- canonical.upsert canonical_key=feature/<name>/rollout doc_class=rollout_plan kind=plan",
      "",
      "7) Link the lifecycle graph (memory.link):",
      "- design references spec",
      "- plan implements spec and depends_on design",
      "- test depends_on plan",
      "- rollout depends_on plan",
      "- spec references app",
      "",
      "8) During implementation:",
      "- store code maps and environment facts via memory.commit (doc_class=code_map/environment_fact)",
      "- store ADRs via memory.commit (doc_class=adr, kind=decision)",
      "- store session snapshots via sessions.end(create_snapshot=true)",
      "",
      "9) Retrieval best practice:",
      "- canonical.outline -> canonical.get_section for precise sections",
      "- memory.search -> memory.get/canonical.get_section for unknown info",
    ].join("\n"),
  },
  {
    name: "memento/template-app-spec",
    title: "Template: App Spec",
    description: "Canonical app-level specification template.",
    text: [
      "# <App> -- Application Specification",
      "",
      "**Artifact type:** App Spec",
      "**Status:** Draft|Accepted|Deprecated",
      "**Owner:**",
      "**Last verified:**",
      "**Confidence:** High|Medium|Low",
      "",
      "## Overview",
      "## Goals",
      "## Non-goals",
      "## Requirements",
      "### Functional",
      "### Non-functional (NFRs)",
      "## Architecture overview",
      "## Observability requirements",
      "## Rollout and deprecation",
      "## Open questions",
    ].join("\n"),
  },
  {
    name: "memento/template-feature-spec",
    title: "Template: Feature Spec",
    description: "Feature specification template.",
    text: [
      "# Feature: <Name> -- Specification",
      "",
      "**Artifact type:** Feature Spec",
      "**Status:** Draft|Proposed|Accepted|Implemented",
      "**Owner:**",
      "**Last verified:**",
      "**Confidence:** High|Medium|Low",
      "**Related:** app, feature/<name>/design, feature/<name>/plan, ADRs",
      "",
      "## Problem statement",
      "## Goals",
      "## Non-goals",
      "",
      "## Requirements",
      "### Functional",
      "### UX/API (as applicable)",
      "### AuthZ/AuthN rules",
      "### Edge cases",
      "### Failure modes",
      "",
      "## Acceptance criteria",
      "- [ ] ...",
      "",
      "## Observability requirements",
      "## Rollout considerations",
      "## Open questions",
    ].join("\n"),
  },
  {
    name: "memento/template-design-doc",
    title: "Template: Design Doc",
    description: "Design doc template for a feature.",
    text: [
      "# Feature: <Name> -- Design Doc",
      "",
      "**Artifact type:** Design Doc",
      "**Status:** Draft|Proposed|Accepted",
      "**Owner:**",
      "**Last verified:**",
      "**Confidence:**",
      "**Related:** feature/<name>/spec, feature/<name>/plan, arch/overview, ADRs",
      "",
      "## Context and constraints",
      "## Current state",
      "## Proposed design",
      "### Data flow",
      "### Components/modules and responsibilities",
      "### Interfaces (APIs/events)",
      "### Data model changes",
      "### Error handling strategy",
      "### Security considerations",
      "",
      "## Alternatives considered",
      "## Tradeoffs",
      "## Operational impact",
      "## Open questions",
    ].join("\n"),
  },
  {
    name: "memento/template-architecture-doc",
    title: "Template: Architecture Doc",
    description: "System architecture reference template.",
    text: [
      "# Architecture -- <Topic>",
      "",
      "**Artifact type:** Architecture Doc",
      "**Status:** Draft|Accepted|Deprecated",
      "**Owner:**",
      "**Last verified:**",
      "**Confidence:**",
      "",
      "## Context",
      "## System overview",
      "## Components and responsibilities",
      "## Data flow",
      "## Interfaces",
      "## Security and compliance",
      "## Operational considerations",
      "## Open questions",
    ].join("\n"),
  },
  {
    name: "memento/template-implementation-plan",
    title: "Template: Implementation Plan",
    description: "Implementation plan template.",
    text: [
      "# Feature: <Name> -- Implementation Plan",
      "",
      "**Artifact type:** Implementation Plan",
      "**Status:** Draft|Accepted|In Progress|Done",
      "**Owner:**",
      "**Last verified:**",
      "**Confidence:**",
      "**Related:** feature/<name>/spec, feature/<name>/design",
      "",
      "## Milestones",
      "## Work breakdown (ordered)",
      "For each task:",
      "- Inputs/outputs",
      "- Files/modules touched",
      "- Tests to add",
      "- Risks and rollback",
      "",
      "## Testing strategy",
      "## Migration plan (if any)",
      "## Observability additions",
      "## Rollout plan pointer",
      "## Open questions",
    ].join("\n"),
  },
  {
    name: "memento/template-test-plan",
    title: "Template: Test Plan",
    description: "Test plan template.",
    text: [
      "# Feature: <Name> -- Test Plan",
      "",
      "**Artifact type:** Test Plan",
      "**Status:** Draft|Accepted|Complete",
      "**Owner:**",
      "**Related:** feature/<name>/spec, feature/<name>/plan",
      "",
      "## Test scope",
      "## Unit tests",
      "## Integration tests",
      "## E2E tests",
      "## Failure injection / chaos",
      "## Performance tests",
      "## Acceptance checklist",
      "- [ ] ...",
    ].join("\n"),
  },
  {
    name: "memento/template-rollout-plan",
    title: "Template: Rollout Plan",
    description: "Rollout plan template.",
    text: [
      "# Feature: <Name> -- Rollout Plan",
      "",
      "**Artifact type:** Rollout Plan",
      "**Status:** Draft|Approved|Executing|Complete",
      "**Owner:**",
      "**Related:** feature/<name>/plan, runbooks, dashboards",
      "",
      "## Prerequisites",
      "## Rollout steps",
      "## Feature flags",
      "## Monitoring signals",
      "## Rollback criteria",
      "## Rollback steps",
      "## Post-rollout verification",
    ].join("\n"),
  },
  {
    name: "memento/template-adr",
    title: "Template: ADR",
    description: "Architecture decision record template.",
    text: [
      "# ADR <NNNN>: <Title>",
      "",
      "**Artifact type:** ADR",
      "**Status:** Proposed|Accepted|Superseded",
      "**Date:**",
      "**Owner:**",
      "**Confidence:**",
      "**Related:** feature/<name>/spec, design docs, PRs",
      "",
      "## Context",
      "## Decision",
      "## Alternatives considered",
      "## Rationale",
      "## Consequences",
      "## Follow-ups",
    ].join("\n"),
  },
  {
    name: "memento/template-code-map",
    title: "Template: Code Map",
    description: "Code map template.",
    text: [
      "# Code Map -- <Project/Service>",
      "",
      "**Artifact type:** Code Map",
      "**Status:** Current|Needs update",
      "**Last verified:**",
      "**Confidence:**",
      "**Related:** app, arch/overview, env/registry",
      "",
      "## Repo layout",
      "## Key modules and responsibilities",
      "## Entry points",
      "## Common workflows (run/test/migrate)",
      "## Gotchas",
    ].join("\n"),
  },
  {
    name: "memento/template-session-snapshot",
    title: "Template: Session Snapshot",
    description: "Session snapshot template for sessions.end(create_snapshot=true).",
    text: [
      "# Session Snapshot -- <Date>",
      "",
      "**Artifact type:** Session Snapshot",
      "**Owner:**",
      "**Focus:**",
      "**Related:** features, PRs, docs",
      "",
      "## Summary",
      "## Decisions",
      "## Changes made",
      "## Open questions",
      "## Next steps",
    ].join("\n"),
  },
  {
    name: "memento/template-runbook",
    title: "Template: Runbook",
    description: "Operational runbook template.",
    text: [
      "# Runbook -- <Service>/<Task>",
      "",
      "**Artifact type:** Runbook",
      "**Owner:**",
      "**Last verified:**",
      "**Confidence:**",
      "",
      "## Preconditions",
      "## Procedure",
      "## Monitoring",
      "## Rollback",
      "## Validation",
    ].join("\n"),
  },
  {
    name: "memento/template-troubleshooting",
    title: "Template: Troubleshooting",
    description: "Troubleshooting template.",
    text: [
      "# Troubleshooting -- <Topic>",
      "",
      "**Artifact type:** Troubleshooting",
      "**Owner:**",
      "**Last verified:**",
      "**Confidence:**",
      "",
      "## Symptoms",
      "## Root cause",
      "## Fix",
      "## Prevention",
      "## Follow-ups",
    ].join("\n"),
  },
];

export function registerPrompts(server: McpServer) {
  for (const prompt of PROMPTS) {
    server.registerPrompt(prompt.name, {
      title: prompt.title,
      description: prompt.description,
    }, async () => ({
      messages: [
        {
          role: "user",
          content: {
            type: "text",
            text: prompt.text,
          },
        },
      ],
    }));
  }
}

export function listPromptNames(): string[] {
  return PROMPTS.map((prompt) => prompt.name);
}
